import os

SQLALCHEMY_DATABASE_URI = '<DB URI>'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_RECYCLE = 299
SQLALCHEMY_POOL_TIMEOUT = 20
SECRET_KEY = os.urandom(24)
SESSION_TYPE = 'filesystem'